### ISSUE TITLE
DOC/DEV: test `bash tests/builds/runner.sh` not mentioned in dev docs

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1020]
There seems to be a test that is only run in CI but missing from the dev documentation.

It'd be great if the person who added the line to the CI config `- run: bash tests/builds/runner.sh` could explain how to do this locally and what is being tested. I think it was @victorlin.

Thanks!

I think it was in commit 092879ba454cc31e8f06c975340ad199ece08f50

Example where this test fails and I don't immediately understand why: https://github.com/nextstrain/augur/runs/7766923240?check_suite_focus=true#step:11:258

**Comment by tsibley** [comment]
`tests/builds/runner.sh` was added in 2710dbceac4ca433d86567d7995a1c9687eb797a by @jameshadfield to the Travis CI config.

It was first mentioned in `DEV_DOCS.md` in e17be15 by @huddlej and then subsequently reworked in 0878320 and 070c6a7.

Its invocation was migrated from Travis CI → GitHub Actions in 092879b by @victorlin, as you noted.

It was (incidentally?) removed from `DEV_DOCS.md` in f1ae13e by @victorlin as part of other changes.

**Comment by victorlin** [comment]
Apologies for not responding earlier when this came up. `tests/builds/runner.sh` was used to run test workflows using Snakemake. Those have since been removed in #1302, including the script itself.

The DEV_DOCS mention was removed in f1ae13e9a76d6e5aec8777de5e4f3c0326a801e8 because the step "Run `devel/test`" included invocation of that script.
