### ISSUE TITLE
Add support for masking gap characters

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#1043]
### Context
We occasionally pass sequences to augur ancestral (or other downstream tools) that include gap characters (`-`) that should actually be missing base characters (`N`). Since "augur ancestral --infer-ambiguous" doesn't actually infer states at gap characters and instead only works on N characters, the resulting output can be surprising/confusing.

### Description
One solution to the problem would be to allow users to mask gap characters with `augur mask` through a new argument like `--mask-gaps`. The closest equivalent of this functionality is the `--mask-invalid` flag, but we consider `-` to be a valid nucleotide character and would need to treat these as a special case.

### Examples
```
augur mask --sequences aligned.fasta --mask-gaps --output masked.fasta
```

**Comment by rneher** [comment]
Note that `augur align` has a `--fill-gaps` flag.

**Comment by rneher** [comment]
and `augur ancestral` treats terminal gaps as missing data by default. I believe this is sensible behavior. Filling internal gaps by default seems wrong to me.

**Comment by emmahodcroft** [comment]
This was something we discussed at the group meeting when you couldn't attend. The issue is that one may want to include sequences where people have used gaps instead of N for areas of low coverage (not uncommon with SC2). However, only Ns are inferred when doing sequence reconstruction - not gaps (I think this is sensible).

To allow people to choose if they want to try and fill low-coverage 'gaps' with Ns so they can later infer sequences, a proposal was to allow people to choose an option to look for columns of gaps that contain only gaps (no other N or base, suggesting possibility of a real deletion) and turn these to Ns. One would only want to use this in a dataset where any real deletions have sequences with & without the deletion to avoid these getting masked. This wouldn't change default behaviour - only be an option (and hopefully by those who really know what they're asking for).

More discussion with better explanations in: https://github.com/nextstrain/augur/pull/1048

**Comment by jameshadfield** [comment]
Ahh - this is more complicated than I thought when we discussed it at last week's meeting!

* Augur align can fill all gaps. [Looks like](https://github.com/search?q=org%3Anextstrain+%22--fill-gaps%22&type=code) we use this in ebola, zika, WNV, MERS, dengue, mumps... so most builds!
* Augur mask currently doesn't do anything special with gap characters (see #1048)
* nCoV uses a masking script to mask terminal gap characters
* Augur ancestral will infer terminal gaps by default (disable via `--keep-overhangs`), but otherwise respect gaps
* Auspice will treat gaps as gaps, no inference is performed

---

> To allow people to choose if they want to try and fill low-coverage 'gaps' with Ns so they can later infer sequences, a proposal was to allow people to choose an option to look for columns of gaps that contain only gaps (no other N or base, suggesting possibility of a real deletion) and turn these to Ns.

Ahh that's interesting. My PR worked on rows not columns, based on the realisation that a lot of pipelines just use the gap character when they mean missing data, resulting in genomes without a single N. A quick scan of 100k representative nCoV sequences indicate a third of them have gaps but no Ns; perhaps some of them are truly complete genomes with actual gaps, but I'm dubious as to how many there are. As far as I know there's no way to know when you only have access to the consensus sequence.

**Comment by emmahodcroft** [comment]
Yea, I think I misunderstood this when we discussed it in the meeting & read the github discussion without the Slack (my bad!). I definitely see this as being a thing for SC2. I think my main question now would be -- is this something that's generalizable to other pathogens (will people know enough about them, be confident that gaps are not real but used as fillers) to add it somewhere to augur, or should we just be making a script that does this nicely for SC2 as a more specific use-case?

**Comment by jameshadfield** [comment]
Revisiting this I think documenting the functionality we have is the better way to solve this, and have done so via [this PR](https://github.com/nextstrain/docs.nextstrain.org/pull/158).
