### ISSUE TITLE
augur modular conda errors

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#142]
Conda install is not working on current augur master (`493250ca100f6f9ea0d8228f8ad8668a30bdfbea`). 

Steps to reproduce:
```
conda create -n nextstrain python=3.6
source activate nextstrain
pip install --process-dependency-links .
```

* `which augur` indicates it's been installed as a python package (and this doesn't exist outside of this conda env)
* `augur parse -h` shows out-of-date arguments , so that running the zika snakefile results in `augur: error: unrecognized arguments: --output-sequences results/sequences.fasta --output-metadata results/metadata.tsv`

Running `python setup.py install` to try in vain to update augur results in a successful install but running `augur -h` results in
```
Traceback (most recent call last):
  File "/Users/james/miniconda3/envs/nextstrain/bin/augur", line 4, in <module>
    __import__('pkg_resources').run_script('augur==0.1.0', 'augur')
  File "/Users/james/miniconda3/envs/nextstrain/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/james/miniconda3/envs/nextstrain/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1425, in run_script
    .format(**locals()),
pkg_resources.ResolutionError: Script 'scripts/augur' not found in metadata at '/Users/james/miniconda3/envs/nextstrain/lib/python3.6/site-packages/augur-0.1.0.dist-info'
```
(note that `python bin/augur -h` works fine)

P.S. out-of-date augur parse help (out of date c/w `python bin/augur parse -h`)
```
usage: augur parse [-h] --sequences SEQUENCES [--fields FIELDS [FIELDS ...]]
                   [--output OUTPUT] [--metadata METADATA] [--sep SEP]
                   [--fix-dates {dayfirst,monthfirst}]

optional arguments:
  -h, --help            show this help message and exit
  --sequences SEQUENCES, -s SEQUENCES
                        sequences in fasta format (default: None)
  --fields FIELDS [FIELDS ...]
                        fields in fasta header (default: None)
  --output OUTPUT       output file (default: None)
  --metadata METADATA   output file (default: None)
  --sep SEP             separator of fasta header (default: |)
  --fix-dates {dayfirst,monthfirst}
                        attempt to parse dates and output them in standard
                        format (default: None)
```

**Comment by tsibley** [comment]
Can you run the following from within the conda env and report back?

```
which pip
pip --version
python3 -c 'import setuptools; print(setuptools.__version__)'
```

**Comment by tsibley** [comment]
Hmm, this line in your stacktrace:

```
  File "/Users/james/miniconda3/envs/nextstrain/bin/augur", line 4, in <module>
    __import__('pkg_resources').run_script('augur==0.1.0', 'augur')
```

indicates to me that augur's `bin/augur` isn't getting installed as-is, but instead a stub bin script is.  Normally those are only installed for `entrypoints` items in `setup.py`.  This makes me suspect some version difference in your Python toolchain.

**Comment by jameshadfield** [comment]
@tsibley 

```
which pip
/Users/james/miniconda3/envs/nextstrain/bin/pip
```

```
pip --version
pip 10.0.1 from /Users/james/miniconda3/envs/nextstrain/lib/python3.6/site-packages/pip (python 3.6)
```

```
python3 -c 'import setuptools; print(setuptools.__version__)'
39.2.0
```
(Note that `python -c ...` produces the same result)

**Comment by jameshadfield** [comment]
SOLVED :) Massive thanks @jlhudd for talking me through everything.

Somehow, an "old" version of augur code was being installed --
i.e. the augur source code in the conda environment was different to that in the `augur/augur` directory, and bash-accessible augur (`/Users/james/miniconda3/envs/nextstrain/bin/augur`) was different to `augur/bin/augur`.


This was because this "old" version existed in `augur/build` (gitignored, generated by `python setup.py install`), and
pip / python chose to use this old, pre-built version over the (newer) source code in `augur/augur/*py`.
Removing the `/build` directory sorted everything out.


Interestingly, modifying source code and re-running `python setup.py install` correctly updated things (i.e. didn't use the `build` directory code).



P.S. Some other things we noticed on our journey this morning:
* re: `pip install --process-dependency-links .`, Dependency Links processing has been deprecated and will be removed in a future release.
We used `python setup.py install` which was both more explicit (indicating that setup.py was being used) and also installed the treetime egg.
* The pip install compiles the dependen

**Comment by tsibley** [comment]
I'm glad you were able to move forward. We need to support pip because is the standard bread-and-butter of Python packaging, but we should also support conda. That might be maintaining a conda environment file that is kept up to date with setup.py or making sure that pip install into conda works.

Some thoughts your final points:

> Dependency Links processing has been deprecated and will be removed in a future release.

There are several [on-going discussions](https://github.com/pypa/pip/issues/4187) about this in the Python/pip community. The general consensus from a practical standpoint seems to be that it should be deprecated, but not before pip supports requirements from version control. There are some technical reasons it does not right now. It seems safe to use for now, and we can adopt the future solution when it's available. Right now there is not another solution. We can also stop using it if TreeTime gets published as a proper package to PyPi.

> We used python setup.py install which was both more explicit (indicating that setup.py was being used) and also installed the treetime egg.

`python setup.py install` is not generally the recommended way to do an install. It is, ultimately in some form, what pip is doing under the hood, but pip layers additional functionality on top. `pip install` always uses `setup.py` to install packages; this is how Python packages work. It's not a weird obfuscation.

> The pip install compiles the dependencies (taking a long time), whereas a conda install would pull down precompiled versions.

pip will use pre-built versions called "wheels" when available, but they aren't always available for some of our older dependency versions.  If we make an effort to upgrade those dep versions and ensure they work, we should also benefit from having pre-built versions available.
