### ISSUE TITLE
How to disable indel trimming with augur align

### ISSUE THREAD

**Issue by swantan** [nextstrain/augur#1480]
Hi, I am working on a bacteria project (Group A Strep) and wanting to construct a Nextstrain instance. However, when I did augur align, it automatically trimmed off gaps within sequences with regards to the reference sequence. My command is as below

`augur align --sequences input.fasta --output output.fasta --nthreads 4 --reference-sequence ref.fasta --remove-reference`

When I review the documentation on augur align, the argument `--fill-gaps false` did not work.  How do I add an argument to disable gap trimming function? 

Thank you and I appreciate for any help!! 
Swan

**Comment by jameshadfield** [comment]
I'd be hesitant to suggest `augur align` (and the programs it uses, such as `mafft`) for a bacterial genome alignment unless you are confident it's the right tool. Reference-based mapping would be more typical, although it's been a few years since I was doing this work.


> it automatically trimmed off gaps within sequences with regards to the reference sequence

> the argument `--fill-gaps false` did not work.

Could you say more about what is not working here? We always strip out insertions relative to the reference, and `--fill-gaps` controls whether we replace gaps in the alignment with "N" to indicate ambiguous sites after any insertions have been removed.

**Comment by swantan** [comment]
Thank you so much for your insights, @jameshadfield! I think I have mistakenly treated --fill-gaps as parameter that could turn out trimming out insertions. The sequences have true indels, I expected the gaps would not be trimmed but it returned a perfect alignment in the output. Good to know that `augur align` will trim out indels no matter what, so it might not be an appropriate tool here. I will reconsider my choice or try to remove the reference sequence.

Thank you once again!
Swan
