### ISSUE TITLE
CI: linkcheck fails occasionally due to fasttree link

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#1621]
### Current Behavior
I've noticed that linkcheck occasionally makes CI fail.

The only broken link I could find in logs is this:

```
(installation/installation: line    9) broken    http://www.microbesonline.org/fasttree/ - 403 Client Error: Forbidden for url: http://www.microbesonline.org/fasttree/
```

https://github.com/nextstrain/augur/actions/runs/10706830674/job/29685454019#step:6:160

Update: seems just flaky, rerunning fixed it. Maybe we could wrap this step in a retry to deflake if it bothers us that CI fails stochastically.

**Comment by tsibley** [comment]
Yeah, see https://github.com/nextstrain/.github/issues/106.

**Comment by corneliusroemer** [comment]
Ah thanks. Why is this in a private repo rather than here in the repo that's actually affected? This means I need to check 2 rather than 1 repo for duplicates?

**Comment by tsibley** [comment]
Right, the code lives there and the issue is more broad than Augur (though Augur is where we're most noticing the failures right now). I don't see the need for an open issue here; a closed one serves fine for searching purposes and doesn't clutter the open list. But if you'd like to leave it open, that's fine with me.

> This means I need to check 2 rather than 1 repo for duplicates?

Searching across the org, [e.g.](https://github.com/search?q=org%3Anextstrain+linkcheck&type=issues), rather than within a repo would be easier than searching two repos.

**Comment by corneliusroemer** [comment]
Ah, the thing is the default of searching open issues is the easiest. I _could_ search the org but it requires extra clicks I need to remember. 

Same for closed issue potentially, I would have to alter the default query. I think in principle it should stay open and be marked as "blocked" or "upstream" but this is bikeshedding process and I'm happy with whatever you prefer 😀
