### ISSUE TITLE
NA epitope mutations outlier

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#195]
@huddlej ---

Here's the live H3N2 NA 2y build with epitope mutations colored:

https://nextstrain.org/flu/seasonal/h3n2/na/2y?c=ep

I noticed the color range was odd. This is entirely due to `A/Malaysia/RP1252/2017` which is listed to have 23 epitope mutations:

https://nextstrain.org/flu/seasonal/h3n2/na/2y?c=ep&m=div&s=A/Malaysia/RP1252/2017

However, zooming in on this virus I don't see how this is possible. It shows up as identical to a couple other viruses that have `ep` of 10:

<img width="1056" alt="malaysia" src="https://user-images.githubusercontent.com/1176109/43880278-8eab67e0-9b5c-11e8-9452-442e82d27413.png">

Could you investigate? The whole build is on Rhino if helpful.

**Comment by huddlej** [comment]
Looking at the raw auspice tree JSON, the outlier virus does have several additional mutations corresponding to a 13 amino acid deletion.

```json
"strain": "A/Malaysia/RP1252/2017",
"muts": [
    "deletion 192-231"
],
"aa_muts": {
    "NA": [
        "E64X",
        "I65X",
        "V66X",
        "Y67X",
        "L68X",
        "T69X",
        "N70X",
        "T71X",
        "T72X",
        "I73X",
        "E74X",
        "K75X",
        "E76X"
    ]
}
```

The multiple sequence alignment for the outlier starts like this.

```
>A/Malaysia/RP1252/2017
NNNATGAATCCAAATCAAAAGATAATAACGATTGGCTCTGTTTCTCTCACAATTTCCACA
ATATGCTTCTTCATGCAAATTGCCATCCTGATAACTACTGTAACATTGCATTTCAAGCAA
TATGAATTCAACTCCCCCCCAAATAACCAAGTGATGCTGTGTGAACCAACAATAATAGAA
AGAAACATAACA---------------------------------------ATATGCCCC
AAACCAGCAGAATACAGAAATTGGTCAAAACCGCAATGTGGCATTACAGGATTTGCACCT
```

The 39 nucleotide deletion relative to the reference corresponds to a 13 amino acid deletion.

Since the epitope mutations metric is intended to count substitutions at epitope sites, we should probably exclude amino acid mutations that result in an “X” from these counts.

**Comment by trvrb** [comment]
Thanks for sussing this out @huddlej. I agree with not counting mutations to "X" in epitope counts. Could you make this change (for both HA and NA)?

**Comment by trvrb** [comment]
I'm testing fa17a908eca125ee156de4d5694359484da213f7 on rhino now. Thanks John.
