### ISSUE TITLE
ValueError on traits.py caused by recent commit

### ISSUE THREAD

**Issue by martinbaste** [nextstrain/augur#196]
Hi there,

we just updated to the latest version of augur and traits.py threw the following error:

```
  File "augur/traits.py", line 139, in run
    field=column, confidence=args.confidence)
ValueError: not enough values to unpack (expected 3, got 2)
```
Reverting the file back to the previous commit apparently solved the issue. The commit that last changed the file is:
bd3f5db1

**Comment by rneher** [comment]
my bad, thanks for catching this. The error probably happened after mugration inference failed because of too many or no states, right? I had forgotten to increase the number of `None`s that get return from 2 to 3. could you check whether

e778d3850f1b412f2f6ff3a03e2fe781cdd158fe

fixes your issue?

thanks!

**Comment by martinbaste** [comment]
It does, thanks for the quick fix!
