### ISSUE TITLE
possible bug in nucleotide reconstruction

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#199]
I'm unsure why the following mutation has been inferred to have occurred ~150 times instead of the more parsimonious reconstruction.

![image](https://user-images.githubusercontent.com/8350992/43926944-b96fd770-9be0-11e8-8491-a44b2a5b9204.png)
![image](https://user-images.githubusercontent.com/8350992/43926958-c36d1f76-9be0-11e8-89c2-6e9eef9c809e.png)

**Comment by emmahodcroft** [comment]
So most of these are going to N - which means there wasn't a call, the base is unknown. For TB I don't allow reconstruction of these ambig bases at the tips because when sequences are really close (almost clonal) it makes it look like there's more resolution then there actually is (it looks like there's a clear signal for distinguishing the sequences when there really isn't - it's mostly Ns). 

However, this shouldn't show up in the counts/entropy, as that's not good either! Would it be ok to just exclude mutations to N?

**Comment by emmahodcroft** [comment]
As a better example of this - from the Walker 2018 TB outbreak, with reconstruction of ambig bases, it looks like there's some potentially interesting structure to the sequences:
![image](https://user-images.githubusercontent.com/14290674/43927463-e88709be-9c2d-11e8-9d6a-213470af3da4.png)

But actually, most of them are no-call:
![image](https://user-images.githubusercontent.com/14290674/43927508-11aa82c6-9c2e-11e8-9a15-d2418f6a446a.png)

**Comment by jameshadfield** [comment]
I agree that you want Ns shown on the tree... so excluding them from the entropy calculations seems sensible.

**Comment by jameshadfield** [comment]
closed by https://github.com/nextstrain/auspice/pull/621
