### ISSUE TITLE
Giving list of 2 nodes  as --root in refine breaks run

### ISSUE THREAD

**Issue by alliblk** [nextstrain/augur#262]
I'm working on re-building zika-colombia, and the 2-node rooting I used to use as the `--root` input for `augur refine` seems to be broken. From the help message it looks like `--root` can take a method (like `best`), a single node, or a list of 2 nodes indicating a monophyletic clade. I've verified that everything runs smoothly if I give a single node or if I give `best`. However giving 2 nodes breaks with the error `TypeError: unhashable type: 'list'`. I think it's possible that the TreeTime dev has deprecated this functionality, but if so then the `--help` should probably be amdended. Full traceback is below.

```
Traceback (most recent call last):
  File "/usr/bin/augur", line 11, in <module>
    load_entry_point('nextstrain-augur', 'console_scripts', 'augur')()
  File "/nextstrain/augur/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/nextstrain/augur/augur/__init__.py", line 66, in run
    return args.__command__.run(args)
  File "/nextstrain/augur/augur/refine.py", line 187, in run
    clock_filter_iqd=args.clock_filter_iqd)
  File "/nextstrain/augur/augur/refine.py", line 67, in refine
    vary_rate=vary_rate, **kwarks)
  File "/usr/lib/python3.6/site-packages/treetime/treetime.py", line 165, in run
    if self.reroot(root=root)==ttconf.ERROR:
  File "/usr/lib/python3.6/site-packages/treetime/treetime.py", line 412, in reroot
    if root in rerooting_mechanisms or root in deprecated_rerooting_mechanisms:
TypeError: unhashable type: 'list'
    Error in rule refine:
        jobid: 3
        output: results/tree.nwk, results/branch_lengths.json
```

**Comment by emmahodcroft** [comment]
@rneher It looks like you worked on this in `treetime` already. I can make this an separate issue if you/others would prefer, but it's tied in: rerooting options are pretty confusing.

Options listed from `augur refine -h`:
- `best`, `residual`, `rsq`, `min_dev`
- `<node>` (give one node name)
- `[<node>, <node>]` (give a list of nodes, reroot to MRCA)
- Says the default is 'None' (does not say what this means - I think `root=None` passed to `treetime.run` means no rerooting takes place?)

Options from `treetime -h`:
- `min_dev`, `min_dev_ML`, `least-squares`, `ML`
- `<node>`
- No mention of list of nodes (though it should work now)
- Does not say what the default will be (though `--keeproot` just below it implies the default is rerooting, and `treetime` sets `--reroot` to 'best' by default (which seems to be `least-squares`)

Options listed in `reroot` method in `treetime.py`:
- `ML`, `best`, `least-squares`, `oldest`
- `<node>` and `[<node>, <node>]`
- (No mention of `min_dev` or `min_dev_ML`)

Options listed at top of `treetime.py`:
- `min_dev`, `min_dev_ML`, `best`, `least-squares`, `ML`

It seems that possibly the defaults for `augur refine` and `treetime` for rerooting are different - though I can't be certain. If so, this is perhaps confusing. 

It might be good to explicitly state what kind of rooting (or not) is happening, each time, so that users are very clear on the behaviour (in particular, what `best` means, if no rerooting is happening, and what rerooting is/isn't happening if nothing is specified) - particularly since it tends to change...

Happy to help with this, but would need a bit of clarification on desired behaviour vs current behaviour to get started.

**Comment by emmahodcroft** [comment]
@rneher I think your recent push to `treetime` should fix this for @alliblk ?

**Comment by huddlej** [comment]
@alliblk Does Emma's [rooting PR](https://github.com/nextstrain/augur/pull/263) fix this issue for your Zika builds?

**Comment by rneher** [comment]
Closing this now. There was an issue with how these arguments are passed on to treetime, but this should be fixed now.
