### ISSUE TITLE
Add bootstrapping support for the trees

### ISSUE THREAD

**Issue by wqshi** [nextstrain/augur#267]
It's quite common to evaluate the reliability of trees using bootstrapping approach. Most of the tree packages support this function. But I find augur doesn't support this. Maybe it's due the slow speed of bootstrapping. IQ-TREE has some fast version of bootstrapping. So I still want a valid tree even it might be slower.

**Comment by rneher** [comment]
The main reason we currently don't support bootstrap values is that they are not handled in the downstream analysis (timetree estimation) and auspice visualization. But for non-timetree application, this would definitely be useful.

**Comment by huddlej** [comment]
@wqshi As of [augur 5.3.0](https://github.com/nextstrain/augur/releases/tag/5.3.0) we added support for passing custom arguments to the underlying tree inference software associated with your chosen `--method`. This allows you to run IQ-TREE with any arguments you like. For example, you can run standard non-parametric bootstrapping with 200 replicates like so:

```
augur tree \
  --alignment results/aligned.fasta \
  --method iqtree \
  --output tree_raw.nwk \
  --nthreads 4 \
  --tree-builder-args="-b 200"
```

The final output Newick file will still be the maximum-likelihood tree (the file with the `.treefile` extension), but you can find the corresponding bootstrap files for the given input alignment in `results/aligned-delim.fasta.boottrees` and `results/aligned-delim.fasta.contree`.

I'm going to close this issue now, but if you feel this feature does not fully address your original request, you can reopen the issue here. Thank you!
