### ISSUE TITLE
Remove augur export errors related to author info

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#274]
Currently, `augur export` complains loudly when strains don't have `author` info. This is really just important for building Nextstrain, where we want to be very strict about giving credit. For other folks running augur/auspice on their own data, it matters less. I think we can remove this error.

```
Error - ZK_YN001 had no authors
Error - ZZ_1 had no authors
Error - Zhejiang04 had no authors
Error - _CCMU01/2016 had no authors
Error - mex07/Mexico/2016 had no authors
Error - mex39/Mexico/2016 had no authors
Error - mex48/Mexico/2016 had no authors
Error - mosquito/Haiti/1682/2016 had no authors
Error - mosquito/Haiti/1855/2016 had no authors
Error - mosquito/Haiti/1919/2016 had no authors
```

**Comment by peterwc** [comment]
Do we only need to supply an "author" column in the metadata to suppress the warning?

**Comment by trvrb** [comment]
@peterwc: Yes, supplying `author` column in metadata with text present should suppress the warning.

**Comment by jameshadfield** [comment]
@emmahodcroft @trvrb can I ask you to add a dataset to augur's test builds without authors so we can ensure this is fixed with `augur export v2`

**Comment by emmahodcroft** [comment]
Weirdly there was already a metadata file without authors in the `tb` test data folder 🤔

I went ahead and added to the snakefile so that there's a run without authors. However, this never actually made an error - it just printed "Error" to the screen a lot. PR #370 

Anyway, I've changed this to just give a 'Warning' and a count of how many don't have author information:
![image](https://user-images.githubusercontent.com/14290674/64263320-c1012100-cf2f-11e9-8a21-645324981118.png)

This does *not* fix the huge "Error" (not really an error, as in, `export` completes successfully) list you get if you have some discrepancies in titles....
(ex: "Next-generation Sequencing of Enterovirus D68" and "Next Generation Sequencing of Enterovirus D68")
![image](https://user-images.githubusercontent.com/14290674/64263874-b1360c80-cf30-11e9-8b63-914036c4f0d6.png)

**Comment by emmahodcroft** [comment]
My bad, the file with missing author info was just on my computer! Added now.

Also added PR
