### ISSUE TITLE
Export V2: True & False Metadata Doesn't Work

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/augur#299]
I haven't tested this in V1, but since we've gotten this far and are about to push to V2, I suggest maybe not to worry about it.

If a column in metadata consists only of values 'True'/'False'/'true'/'false', `pandas.read_csv` automatically parses this to boolean values.
(`utils.py` `read_metadata`)

Later, in `export.py` `transfer_metadata_to_strains`, we transfer traits by asking:
` if trait in raw_data and raw_data[trait]: `
If the _value_ of that trait is `False` then the value for that trait will not be transferred... So this just disappears. Then all values are `True`. This unexpectedly results in a Legend will all values of '1':
![image](https://user-images.githubusercontent.com/14290674/59860657-a29f7680-937f-11e9-8fb6-ca49174501dd.png)

But I can debug this further once we decide on a fix for this initial problem.

It would be good if there's an option in `pandas.read_csv` that prevents this conversion somehow...? So that we can 'manually' convert this to 'our kind of boolean' later? If not, I'm unsure how to handle. Ideas?

**Comment by tsibley** [comment]
Two changes could be made, not necessarily exclusive to each other:

1. Test `raw_data.get(trait) is not None` instead of `trait in raw_data and raw_data[trait]`. This is good practice if valid values are expected to be falsey, such as `False` or `0`. I expect traits with an integer value of 0 would also be affected by the current conditional.
2. Pass empty lists to `true_values` and `false_values` to avoid conversion to boolean.

**Comment by emmahodcroft** [comment]
I tried 2, but it didn't seem to help! I didn't pursue it much though :)
