### ISSUE TITLE
Refine: Unable to Read Tree Not Handled

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/augur#302]
in `refine.py`:

```
    for fmt in ["newick", "nexus"]:
        try:
            T = Phylo.read(args.tree, fmt)
            node_data['input_tree'] = args.tree
            break
        except:
            pass
    if T is None:
        print("ERROR: reading tree from %s failed."%args.tree)
        return 1
```

I just passed a non-existent file name - I imagine the idea is that I get the above error. However, instead I get 

```
  File "/mnt/c/Users/Emma/bash/github/augur/augur/refine.py", line 138, in run
    if T is None:
UnboundLocalError: local variable 'T' referenced before assignment
```

I'm guessing we need to not pass, and instead print the error and exit?

```
    for fmt in ["newick", "nexus"]:
        try:
            T = Phylo.read(args.tree, fmt)
            node_data['input_tree'] = args.tree
            break
        except:
            print("\n\nERROR: reading tree from %s failed."%args.tree)
            return 1
    if T is None:
        print("\n\nERROR: reading tree from %s failed."%args.tree)
        return 1
```

This seems to work, as long as there's no obvious problem with handling it this way (is there a reason we pass here?).

**Comment by tsibley** [comment]
:+1: for handling this within the except instead of passing. Can we remove the `if T is None` block all together if we handle the error within the except? I think we could. 

IIRC, there are a couple places that do this try + pass + if None pattern in augur:

```python
try:
    X = ...
except:
    pass
if X is None:
    ...
```

And I've previously found them a bit weird, but didn't want to change them at the time. The only reason I can think of to `pass` would be if `Phylo.read` can return `None` but not throw an exception. Then the pattern of passing and testing for None consolidates the error handling. But as you've seen, care must be taken with the scoping of variable declaration. A quick test of `Phylo.read` indicates that it throws an error on an empty file anyway.

Thanks for digging into this!

**Comment by emmahodcroft** [comment]
From a quick look at `Phylo.read` (is [this ](https://biopython.org/DIST/docs/api/Bio.Phylo._io-module.html#read)the right one?) I do not think it can return `None`. 

I also tried giving it a file which is empty - it throws an exception. 

If your tree file contains only `();` the above step works fine (no error or exception - the error comes later, in `TreeTime`). 

I have also been confused by the try + pass + if None pattern, but assumed it knew something I didn't. In other situations reading different things, this may need to be checked out further - it might make more sense. But I think for instances of `Phylo.read` we'd be better to handle the exception.

**Comment by tsibley** [comment]
I agree. :-)

**Comment by rneher** [comment]
I think the original reason for doing this this way was to iterate multiple common formats, catch errors that arise when attempting to parse using the wrong format, break out once successfully loaded a tree, and throw and error if still None after all formats are tried. This of course requires that `T=None` is assigned before you go into the loop.
