### ISSUE TITLE
Check 3rd Party Tools Installed when Called

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/augur#329]
From PR #321 and Issue #320 : 

If `vcftools` is not installed and `augur filter` is run, it does not give an error. It instead produces a `filtered.vcf.gz` file containing 1 blank line, and this generates weird errors downstream.

Quoting #321:

>The problem is caused because the call is something like:
`vcftools --remove-indv G22696 --gzvcf data/lee_2015.vcf.gz --recode --stdout | gzip -c > results/filtered.vcf.gz`
>
>When the `vcftools` part fails, the `gzip` part goes ahead and zips up nothing, creating the one-blank-line file.
>
> Interestingly, this is not caught by `utils.py` function `run_shell_command` (which is what puts the call through). This function uses `subprocess.check_call` to check the call is successful - but apparently this does not catch `/bin/sh: 1: vcftools: not found`. (I could not find much info about this online; it proved hard to google.)

PR #321 addresses this particular problem with `vcftools`, and `filter`/`mask`, but we call 3rd party programs throughout `augur`, and should perhaps put something more comprehensive in place to check for whether these programs are installed, and give informative error messages to the user:

> It might be preferable to implement this somehow in `run_shell_command` in a more general way, so that any external program call is checked.

I could not take this further myself, but I believe, @tsibley, you initially implemented the good idea of `run_shell_command`? Would you have an idea of how to add 'check program is installed' to this?

(If not, or if you think this isn't actually an issue in other 3rd party calls elsewhere in `augur`, just close this issue!)

**Comment by tsibley** [comment]
The reason why `run_shell_command` doesn't detect any error is that /bin/sh doesn't report an error in its exit code when running the pipeline. This is because shell pipelines like `a | b | c` only report the exit status of the _final_ command (`c`). In our case, `gzip` succeeds, so the shell reports success. Bash has a `pipefail` option (which I enable in ~all shell programs I write) that makes shell pipelines error out if _any_ of the commands fail. More info on this behaviour [in the Bash manual](https://www.gnu.org/software/bash/manual/html_node/Pipelines.html); see the last ¶ there.

As for what augur should do about it, there are a couple options I see:

1. Insist that the shell used by `run_shell_command` is Bash and enable the `pipefail` option. Right now it uses /bin/sh, which may be Bash in sh-compat mode, or it may be some other POSIX-compliant sh. Bash should be installed most everywhere as /bin/bash, but we may run into some environments where it isn't.

2. Bypass the shell entirely by switching from shell command strings to executing programs directly. This is a software engineering best practice and increases overall safety and security in the face of malicious inputs, but it makes the command invocations somewhat more verbose in augur.

Option 2 is where I would push for augur to ultimately go (and what the Nextstrain CLI does), but Option 1 is probably the most pragmatic right now.

**Comment by tsibley** [comment]
I guess there is also a third option: try to detect if a given command or commands are available before running the shell command. But this is by its nature more fragile and prone to false-positives/false-negatives than either of the options above. I think it would be more worthwhile to do 1 or 2 from above.

**Comment by emmahodcroft** [comment]
Thanks for looking into this @tsibley ! That's a much better breakdown of causes and options than I was able to uncover, and I appreciate it :)

I'm happy to go with your recommendation, of ultimately heading towards option 2 but implementing option 1 in the short-term. 

In case of problems with option 1 in some environments, I don't suppose there's some way we could preempt this (Bash != /bin/bash) and (if it fails) display something asking the user to get in touch or make an issue? That would at least allow us to have an idea of how much of an issue it might be among users (how urgent it might be to push towards option 2). But maybe asking for a catch for a catch is a bit too much! :D

**Comment by tsibley** [comment]
@emmahodcroft Would you give PR #350 / branch `shell-pipeline-errors` a spin?
