### ISSUE TITLE
Add (auspice) JSON version explicitly to export JSONs

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#335]

**Comment by jameshadfield** [comment]
https://github.com/nextstrain/augur/blob/v6/augur/export_v2.py#L751

**Comment by trvrb** [comment]
@jameshadfield ---

I'm not sure calling this "version": "2.0" is the best thing. This is because auspice will rapidly go to version 2.1, 2.2, ... 2.38. We do not want to iterate on the schema version to 2.38 (or do we?) And if we did iterate schema to 2.1 whole auspice is 2.38 it will add even more confusion. I'd think better to just use "version": "v2" instead (and not worry about feature bumps). What do you think? Sorry I didn't think of this before.

Cc @tsibley, @emmahodcroft, @richardneher

**Comment by jameshadfield** [comment]
Can someone please take this issue! Thanks 🙏

**Comment by tsibley** [comment]
I agree with @trvrb about just using the major version number (2, 3, 4, etc) for the schema version. It aligns with our desire to have schema versions match major Auspice versions, so all v2 schema are compat with Auspice 2.x.y and vice versa.

**Comment by rneher** [comment]
this is done for v2
https://github.com/nextstrain/augur/blob/v6/augur/export_v2.py#L795

**Comment by jameshadfield** [comment]
Closed by #385
