### ISSUE TITLE
Unwanted colorings are exported in augur v2

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#403]
@jameshadfield @emmahodcroft ---

I discovered this in working on seasonal flu. Here, we have a node data JSON (`distances.json`) that looks like:

```
  "nodes": {
    "A/Aberaeron/5961/2018": {
      "ep": 10,
      "ne": 2,
      "ne_star": 0,
      "rb": 1
    },
```

containing `ep`, `ne`, `ne_star` and `rb`. I want to color by `ep`, `ne` and `rb`, but I don't want to color by `ne_star`. However, if I include `distances.json` in `export v2 --node data` then all 4 attributes are automatically included as colorings, even if none are listed in Auspice config. This results in an annoying "ne_star" entry in the color bys list in Auspice.

I would recommend that if we provide `colorings` in the Auspice config that only elements of this list are actually made into colorings, rather than including everything that's passed into `--node-data`.

**Comment by jameshadfield** [comment]
The interplay between node-data-traits and metadata-traits and config-traits and cmd-line-traits is a bit of a tricky one. I'll see if I can make a flow chart to summarise what's going on. This exact issues has been discussed before and I can't remember the decided outcome (@emmahodcroft?)

**Comment by trvrb** [comment]
I understand that the interplay here is tricky. If auspice config was not passed in or did not have colorings I'd want all attributes in node data JSONs to be active colorings.

**Comment by jameshadfield** [comment]
Here's the current state of the code for traits coming through `augur export v2`. It does seem overly complicated and perhaps now's a good time to think a bit more about it. I know @emmahodcroft spent a lot of time with this and it's not easy!

![v2-coloring-logic](https://user-images.githubusercontent.com/8350992/68554842-85cf2100-048f-11ea-8c3d-6f850f8996ae.png)

**Comment by jameshadfield** [comment]
Here's a potential logic for including color-bys. but it may be too simple. We'd still need to prune-down the node-data JSON keys, else you'll get undesired traits such as `branch_length` if you don't supply a config JSON. Might still need to be some special cases to handle such as clades, but we should document these if needed.

![v2-proposed-coloring-logic](https://user-images.githubusercontent.com/8350992/68556576-b1560980-0497-11ea-9ab3-4af3ea58b021.png)

**Comment by trvrb** [comment]
Thanks so much for diagramming this out James. The proposal looks smart to me (but haven't fully thought things through). One thought:

* I wonder about changing `--color-by-metadata` to `--colorings`. This would make the use of the command line flag basically synonymous with the use of the `colorings` config element. This would be the intentional list of colorings to provide. If `--colorings` absent from command line and `colorings` absent from config, then the behavior of adding all node data JSONs and no metadata.tsv seems smart. But if `--colorings` or `colorings` is provided, just go with the specified list.

**Comment by jameshadfield** [comment]
> I wonder about changing `--color-by-metadata` to `--colorings`

👍 

> ... just go with the specified list.

@emmahodcroft is better positioned to answer this, but I believe the reason this wasn't done is to avoid the frustration of adding a new bit of the analysis (e.g. `augur traits`) and the result not coming through _unless_ you also modify export. I'm somewhat ambivalent here, but i'm also not well placed as I tend to use config files.

**Comment by trvrb** [comment]
One more thing, I'll note that in the case above, if necessary I could easily drop `ne_star` from the node data JSON. This solution wouldn't even be hard to do. I raised this because the existing behavior was surprising to me as user.

**Comment by rneher** [comment]
>  Perhaps now's a good time to think a bit more about it.

3 months ago was a good time to think more about this... We discussed this at length and decided on the current scheme. There are many conflicting objectives and there won't be a default that is 'unsurprising' to everybody. I am hesitant to reopen this. The easiest would be to split the distances into those that are used in export and those that aren't.

**Comment by emmahodcroft** [comment]
Hey guys, unfortunately I can't tackle this right now as I'm on holiday. But James is right, I spent quite a while exploring all the options a while ago, and unfortunately there isn't any simple solution (that I found) that doesn't include some kind of slightly complicated behaviour in some circumstances, if we want config to be overridden and users to not have to explicitly specify every colour by, including those they don't know the internal names for (clades, seq traits, etc). We can indeed be more specific that you can just exclude a json (or something in a json) if you don't want it colored by.
We have already been using this feature, where python scripts write out some trait in json format, pass it to export, and it's in your build immediately - it's pretty cool. 

Anyway, if we are going to reopen this discussion I would really appreciate if we can do so from mid next week when I'm back in Basel, as I worked hard on this and thought it was all agreed, and would like to continue to be involved if we want to discuss further, unfortunately I can't do that this week.

**Comment by trvrb** [comment]
Thanks @rneher and thanks @emmahodcroft! I reread Emma's wonderfully detailed writeup of this entire logic here: https://github.com/nextstrain/augur/pull/346.

I would note that Emma planned for:
>If using config:
>Only entries in config colorings will be used (with type and title used if present, and guessed if not)

This is not current `export v2` behavior. As Richard says, let's not scrap the well thought out logic that Emma has already thought through. I would be in favor of keeping this issue open and aligning with the original logic. This should not be blocking v6 release.

**Comment by emmahodcroft** [comment]
I can check again when I get back but I think the problem here is actually the clarity of the guide. For traits in JSON they are always exported, everything else really only applies to metadata colour by. Otherwise you couldn't use config only and automatic detection for clades etc (people would have to add seq traits etc to config, which had internal names they don't know). But can check again nextweek.

**Comment by emmahodcroft** [comment]
I've looked into this again and yes, the confusion arises because I was not clear enough in my use of colorby.
At the heart of the code (under 'How we decide what's a Colorby'), everything from `--node-data` that's not in `metadata` is an 'auto-colorby'. (I presume these things like `ne_star` are generated within augur, not from metadata.)

This is meet the requirement I outline at the top of that post:

> Users should never have to write names of traits that aren't in their metadata (ex: `clade_membership`) - they are our internal names and users should not have to learn them!

I do think this is a quite important one as it allows us (and others) to have functions that do more complicated things and output 'trait' names that didn't previously exist. The problem with that is that then the user has no idea what they are - leading to the above point (which I think should be true for both CL and `config` use).

I think if we move towards making users explicitly specify everything they want as a colorby, including these kinds of traits, this is will _never not be difficult_ for users, because they're always going to be having to open up JSONS or look into Docs to figure out what the trait name is. And we already know from the current 'config' files that this is a real stumbling block.

In the case above this gets possibly more confusing because of the `config` file rules. Essentially, the generation of the 'auto-colorbys' (things passed via `--node-data` that aren't in metadata [aka internally generated traits]) is neither command-line or `config` - it always happens, and thus can never be overruled like traits in `metadata` can. (It should work that you can change the 'title' and 'type' for these, though.) The only way to remove it is to remove it from the JSON file or not pass in that JSON file.

I think from out side, trying to remember the rules and rectify the two, this gets a bit hairy. But I think from a new user perspective we can present things quite simply:
- If it's in your metadata and you want to colour by it, you have to specify it using `--metadata-color-by` or in the config.
- If it's not in your metadata and you pass it in via a JSON file, it'll be a colorby always. If you don't like that, don't pass in the JSON, or re-run the function excluding that part. You never have to worry about what trait names we came up with behind-the-scenes.

When I wrote this guide the main ways of getting 'trait' information were `traits`, `sequence-traits`, and `clades`. I can't say I know anything about `distances` and maybe that's part of where the problem lies - in `traits` it's easy enough to re-run without a trait (just 'country' instead of 'country region') and it's easy to leave out the JSONS from `sequence-traits` and `clades`. I don't know how this is for `distances`. But, certainly it's true that with this approach, the onus is on us (and other developers) to ensure that what's output is a reasonable colorby and/or that users can specify what is output (to just include what they want).  This could probably be made clearer somewhere!

**Comment by trvrb** [comment]
Thanks for the detailed explanation @emmahodcroft. This makes sense to me and I'd consider this issue closed. I'll proceed with updating seasonal flu to remove the unwanted traits from node data JSONs.

**Comment by emmahodcroft** [comment]
I'll make myself an issue to tackle in future to come up with some guidelines for making new functions that generate 'new traits' so that it's easier to consider how they'll work as colorbys!
