### ISSUE TITLE
Record Filtered and Pruned Sequences

### ISSUE THREAD

**Issue by emmahodcroft** [nextstrain/augur#424]
`filter` was recently improved by displaying the numbers of sequences dropped for different reasons/arguments, and this is super helpful.
However, I'm often receiving requests for exactly which sequences were dropped and for what reason. Currently this is something I have to put together by hand - and as all the info is just displayed to console, it can be hard to trace down as well.

It would be great to include options in both `filter` and `refine` so that the user can ask for a file to be written out giving the names of sequences dropped and the reason.

**Comment by trvrb** [comment]
I think this is a great idea Emma, though I wonder if it could be accomplished with just a '--verbose' flag and writing to standard out.

**Comment by emmahodcroft** [comment]
This might be a naive question but is it possible within snakemake to make standard out for just a few rules go somewhere different than the rest?

I am not so savvy with standard out and digging through to find strains dropped by `refine` (which is already given on standard out) is annoying. But if there's a way to send the output of `filter` and `refine` somewhere specific (apart from the other output) in snakemake, then yes, this would be a fine solution.

**Comment by tsibley** [comment]
@emmahodcroft

> This might be a naive question but is it possible within snakemake to make standard out for just a few rules go somewhere different than the rest?

Maybe I'm misunderstanding what you're asking, but you do this by redirecting stdout within the shell command invocation itself. So instead of:

```
rule foo:
    shell: """
        echo hello world
    """
```

you do:

```
rule foo:
    shell: """
        echo hello world > some-file.log
    """
```

And Snakemake actually has [nice support for log files](https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#log-files) like this, so that the name can be parameterized easily:

```
rule foo:
    log: "some-file-{a_wildcard}.log"
    shell: """
        echo hello world > {log:q}
    """
```

**Comment by trvrb** [comment]
Obviously multiple ways to do things. If I had an analysis where I'm interested in what got dropped, I'd want to write out a log file from the entire Snakemake workflow and then search this file for "filter".

Generally, I imagine this as being less restrictive going forward. There are all sorts of details one could be interested in and writing out files for all details seems onerous.

**Comment by tsibley** [comment]
> If I had an analysis where I'm interested in what got dropped, I'd want to write out a log file from the entire Snakemake workflow and then search this file for "filter".

FYI, Snakemake writes out log files of the entire workflow by default into `.snakemake/log/`.

**Comment by emmahodcroft** [comment]
@tsibley Thanks! That seems like it would do what would be useful. Particularly if `filter` and `refine` can be sent to the same place to consolidate. I would be happy with that for a solution if we can adjust `filter` to have an option to output which sequences are dropped for what reason. (Perhaps `--verbose` as Trevor suggested, or similar.)

**Comment by tsibley** [comment]
@emmahodcroft As long as the `filter` and `refine` steps can't run simultaneously (which I believe is true for all our builds), then you can append to the same file in the second step:

```
rule filter:
    log: "some-file-{a_wildcard}.log"
    shell: """
        echo hello > {log:q}
    """

rule refine:
    log: "some-file-{a_wildcard}.log"
    shell: """
        echo world >> {log:q}
    """
```

Note the use of `>>` instead of `>` in the second step.

**Comment by trvrb** [comment]
My other idea here would be to start our own logging. If you hand `augur filter` a `--log` option that gives it a filename it writes a verbose log to this file. Other augur commands could follow the same logic in including a `--log` option. Might also be possible to have automatic naming of log files, but we obviously have to be careful there to avoid overlap.

**Comment by emmahodcroft** [comment]
@trvrb Two nice things I see about a `--log` option:
1. Naive users can employ it easily without having to know about standard out
2. (I assume) We could specify which alerts and info go to the log and which continue to appear on the console. 
For example, it's very useful to see the big `filter` warning flash up 'ALL SEQUENCES HAVE BEEN DROPPED' or even for me, since I know many of my builds well, if the 'summary' counts of those dropped suddenly spikes or goes to 0 - just tabbing over and glancing at the terminal lets me know all is well during a run. Would be nice to preserve this while being able to send more lengthy and screen-filling list of sequences dropped to another file, out of sight!

**Comment by tsibley** [comment]
A `--log` option sounds fine to me, as long as the default is still to send messages to stdout/stderr. stdout and stderr are such fundamental and universal command-line concepts; breaking them by default would be bad. I'd also expect this `--log` option to be supported globally at the `augur` level, not specific command.

The best way to do the separation of messages by severity level is to start using an actual logging framework (like Python's `logging`) instead of using `print()` statements. This provides flexible handling for writing all messages to the `--log`, if provided, and letting some also go to the terminal.

You can see an example of the `logging` framework [in use here](https://github.com/seattleflu/id3c/blob/4ade1892f98fb97731325ad1c6c2e6bda4c2f98c/lib/id3c/db/__init__.py#L45-L110) (the `LOG.info` and `LOG.error` and `LOG.debug` lines). `LOG` is a logger object defined [at the top of every module](https://github.com/seattleflu/id3c/blob/master/lib/id3c/db/__init__.py#L15), so that messages can be tagged with details of where they were logged from. The logging framework itself (e.g. where messages go, what gets output where) is [configured at the top-level of the application](https://github.com/seattleflu/id3c/blob/master/lib/id3c/__init__.py) for all modules beneath it.

**Comment by roblanf** [comment]
Hi all,

We're working on getting some online phylogenetics going (it will happen on this fork https://github.com/roblanf/augur). As part of that I need to keep constant track of which sequences are removed and why (I'll also be adding some additional methods to filter sequences automatically based on bad alignments and/or trees). What I'll be doing overlaps with this issue, so I thought I'd lay out my plan and seek feedback, in case what I do can also solve this issue.

Roughly speaking the plan is to rewrite the "Filtering steps" of filter.py, to create a pandas dataframe.  https://github.com/nextstrain/augur/blob/e03e1daf4b63afa8aef22bf6b1cf2dc8afe972af/augur/filter.py#L135

The data frame will have one row per sequence, and one column per test. NA if the test wasn't run, 'Failed' if the test was run and the sequence failed, and 'Passed' if the test was run and the sequence passed. 

A final column (which for clarity I guess I'll make the column after the name) will have either a 'keep' or 'exclude' flag, based on simple logic about the combination of tests. (E.g. if you fail all the tests but the user said to keep that sequence anyway, you'll get a 'keep').

The reason for doing it this way is that certain tests are unique to individual sequences, so will never need to be re-run. Other tests are dependent on other sequences (e.g. those based on alignment characteristics or the tree), so will need to be re-run if the underlying data change. 

Since this will be such a small file, my feeling would be to default to keeping it around. If there's a natural place to keep it (I'm not yet on top of where things are kept in augur) please let me know. Or if you think the default should be *not* to keep it, or to force users to specify the location for reading/writing it, then I'm happy to go this way too.

**Comment by roblanf** [comment]
Hi All,

Is there a reason not to just make a dataframe here and output to a csv file. Something like:

one row per sequence
one column per test ('pass', 'fail', or 'NA' if test wasn't run)
an extra column to state whether the sequence was kept or excluded (i.e. full logic of the combined tests)

Such a file would be trivial to produce, and also quite human-readable. It would also make things a bit easier for moving to an online phylogenetics model, because one wouldn't have to re-run any tests on sequences that had already been analysed. E.g. if the csv were provided as optional input to the call to `filter`, it could just skip things it didn't need to do.

**Comment by peterhmasters** [comment]
Hi @emmahodcroft I created a class to handle this behavior leveraging @roblanf 's dataframe ideas. 

(I don't know why it hates this portion of formatting)
`
class TrackFilter:
    """This class tracks which sequences are included or excluded by the filter and the reason why

    :param seqs: A list of sequences to be filtered on
    :type seqs: list

    :Example:

    >>> seqs = ['PRVABC59','COL/FLR_00008/2015','Colombia/2016/ZC204Se']
    >>> test = TrackFilter(seqs)
    >>> assert test.seqs == seqs
    >>> assert test.df.shape == (len(seqs), 3)


    """

    def __init__(self, seqs):
        """Constructor method

        :keyword df tracking sequence name, status to include or not, and the reason for either
        """
        self.seqs = seqs
        # Initializing each sequenced as included and passed all tests
        self.df = pd.DataFrame(
            list(zip(seqs, ["inclusion"] * len(seqs), ["passed"] * len(seqs))),
            columns=["Sequence", "Status", "Reason"],
        )

    def update(self, action, reason, new_seqs):
        """This function updates the dataframe tracking sequences based on if they need to be excluded or included

        :param action: If these are the sequences that to not be removed ('remove'), or the sequenced to be added ("add")
        :type action: str
        :param reason: The reason why are these sequences being added or removed
        :type reason: str
        :param new_seqs: The list of sequenced that need to not be removed or to be added
        :type new_seqs: list
        :return: None
        :rtype: None

        :Example:

        >>> seqs = ['PRVABC59','COL/FLR_00008/2015','Colombia/2016/ZC204Se']
        >>> test = TrackFilter(seqs)
        >>> test.update('remove', 'too short', ['PRVABC59','COL/FLR_00008/2015'])
        >>> assert test.seqs == ['PRVABC59','COL/FLR_00008/2015']


        """
        # Updating the list of sequences, the self.seqs update isn't used anywhere but is future-proofing
        # In case this class could be used to track sequences instead of global variables
        self.seqs = (
            new_seqs
            if action == "remove"
            else self.seqs + list(filter(lambda seq: seq not in self.seqs, new_seqs))
        )
        # Updating the dataframe if the sequence needs to be removed or it needs to be added and the reason why
        self.df = pd.DataFrame(
            map(
                lambda sequence: [
                    sequence[0],
                    "exclusion" if action == "remove" else "inclusion",
                    reason
                    # only updating the Reason if the Status is changing
                    if ((action == "remove") == (sequence[1] == "inclusion"))
                    else sequence[2],
                ]
                # only updating the sequence if it's remove & not in the sequence or add & in the sequence
                if ((action == "remove") != (sequence[0] in new_seqs)) else sequence,
                self.df.itertuples(index=False),
            ),
            columns=["Sequence", "Status", "Reason"],
        )

    def summary(self, text_output, csv_output):
        """Conditionally printing out a text summary and a csv containing filter information

        :param text_output: To print out the text report or not
        :type text_output: Bool
        :param csv_output: To output the csv report or not
        :type csv_output: Bool
        :return: None
        :rtype: None
        """
        if csv_output:
            self.df.sort_values(["Status", "Reason"]).to_csv("Filter_Results.csv")
        if text_output:
            print(self.df.groupby(["Status", "Reason"]).count())

`

I see this being used every place there is a 'seq_keep = tmp' pattern in filter.py, and adding output.update("remove"/"add", reason, tmp) before it.

Are there any other features / things I should change about this implementation? Should the text/csv report be a arg added to filter command?

Let me know!
-Peter

**Comment by peterhmasters** [comment]
I can't push my branch to create a pull request, so I put the files here: https://github.com/peterhmasters/NextStrain_Filter_Info/tree/master/NextStrain_Files

I added the --log functionality as mention by @trvrb / @tsibley / @emmahodcroft : 
`parser.add_argument('--log', help="file destination for filter reasoning if it is wanted.")`

I also added the call functionality I.E. 
`filter_info.update("filter", "excluded by name", tmp)` after every filter block.

I also created a couple test cases of core functionality and making sure it only outputs a file when the user inputs into --log.
