### ISSUE TITLE
Reference sequence not removed when calling augur align

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#454]
This should be able to be replicated by running `snakemake -p results/aligned.fasta` in https://github.com/nextstrain/ncov.

This calls `augur align` with `--remove-reference`. However, reference `MN908947` still appears in output.

This is also replicated by running the same set of commands from https://github.com/nextstrain/zika, wherein `PF13/251013_18` still appears in `results/aligned.fasta`.

**Comment by godotgildor** [comment]
I'm having trouble reproducing this using the Zika example. 

If I run:
`snakemake -p results/aligned.fasta --cores`
 in the zika repository, looking in the `results/aligned.fasta` I do not see an entry for `PF13/251013-18`. 

If I edit the `Snakefile` to remove the `--remove-reference` and then run
`snakemake -p results/aligned.fasta --cores`
the resulting `results/aligned.fasta` includes the entry:
`>KX369547.1 Zika virus strain PF13/251013-18, complete genome`

Did I miss something?

**Comment by huddlej** [comment]
@godotgildor The Zika issue only occurs with the full Zika build and not with the tutorial build. [See the complete description of this issue](https://github.com/nextstrain/augur/pull/456#issuecomment-601476915) for more details.

**Comment by tolot27** [comment]
@godotgildor Please can you rerun your test with the most recent version? The issue should be fixed now.

**Comment by huddlej** [comment]
The solution to Trevor's original issue is partially data-dependent. A fix that would help from the augur side, though, is to change the name field used for reference sequences from `id` to `name`. This would be a breaking change in the sense that any build out in the world that relies on the GenBank record's id instead of name would break. However, this change would also avoid the kind of issue Trevor described and also allow users to provide FASTA references instead of GenBank files in the future.

I'm labeling this as an issue to discuss within the Nextstrain team for now. It doesn't need any further development until then.

**Comment by trvrb** [comment]
I'm going to close this immediate issue as the real issue is as @huddlej says one of naming of Genbank reference sequences. I don't think high priority.
