### ISSUE TITLE
Augur refine

### ISSUE THREAD

**Issue by mesti90** [nextstrain/augur#597]
Is it possible to run augur refine with multiple threads? If not, it would be very useful, as this step seems to be a bottleneck in the nexstrain pipeline.

**Comment by tsibley** [comment]
Hi @mesti90, unfortunately it is not possible to trivially parallelize `augur refine` due to the current internal design of TreeTime (which is what `augur refine` uses). There's discussion of both parallelization and speeding up the algorithmic bottlenecks over at https://github.com/neherlab/treetime/issues/110.
