### ISSUE TITLE
Catch exceptions in the command line interface and print error messages to stderr

### ISSUE THREAD

**Issue by huddlej** [nextstrain/augur#642]
Many augur commands can produce errors that manifest as Python exception tracebacks instead of more user-friendly error messages. As a rule, errors in augur Python modules should raise Exceptions and errors in augur command line interfaces should catch those exceptions and print helpful error messages to `stderr`.

For example, when I run the following filter command with an output directory that does not exist:

```bash
augur filter --sequences results/aligned.fasta --metadata data/metadata.tsv --output fake/test.fasta
```

augur raises a `FileNotFoundError` and prints the traceback to the screen. Instead, the user should see a simple error message and get an appropriate nonzero error code.

**Comment by jameshadfield** [comment]
Is the way to do this with a `augur`-wide exception handling (such as the way we handle [`RecursionError`](https://github.com/nextstrain/augur/blob/master/augur/__init__.py#L71-L77)) or by ensuring that the `run()` function in each augur file (which is essentially the subcommand) is one big `try`/`catch` block?

**Comment by huddlej** [comment]
Either of those approaches could work. Ideally, augur would provide enough details in the error message(s) for users to quickly correct the problem. In the example above, a helpful message would be:

```
Error: The output file `fake/test.fasta` could not be created because the directory `fake` does not exist.
  Create this directory and then try again.
```

Actually, we could choose to handle this example by creating missing output directories for users like Snakemake does.
If one of the inputs were missing instead, a helpful message would be:

```
Error: The input `--sequences`, `results/missing.fasta`, does not exist.
  Check the command that you expected to create this file or update the path to refer to the correct input file.
```

To provide this level of detail in the error message, we would either need to catch the exceptions close to the original calling function in each script (so we know which specific file and type was missing) or annotate the original exception object with these details so the top-level `run` function could report them to the user at the same level that the recursion error gets reported.

**Comment by tsibley** [comment]
> Ideally, augur would provide enough details in the error message(s) for users to quickly correct the problem.

Yes, :100: to this.

> Actually, we could choose to handle this example by creating missing output directories for users like Snakemake does.

There is some benefit to not auto-creating output dirs, as it avoids sending output to an unintended place (e.g. due to typos during interactive use). I think of this as akin to a programming language requiring that variables are declared and initialized before first-use. Especially as Snakemake and other workflow systems will typically do the auto-creation, I think nicer to keep it in their control. This also fits conceptually with the workflow system cleaning up partial outputs after failure.

> …or annotate the original exception object with these details so the top-level run function could report them to the user at the same level that the recursion error gets reported.

An approach I've taken in the past is to create a top-level custom exception class, e.g. `AugurError`, that can be specifically caught by the top-level `run()` (like `RecursionError` is). That top-level class can then be subclassed as necessary, although often subclasses aren't needed if common class attributes are supported to, e.g. provide the description, possible solutions, etc.

**Comment by victorlin** [comment]
This has been resolved by additions to the [top-level exception handler](https://github.com/nextstrain/augur/blob/ff5f8802f66d42c4f07693fe4f22802139c9da37/augur/__init__.py#L63-L99) such as 2342f07b75f2ba9953cab8254ebef3d5febb5b5d, 59353f1cfe4bb59f462af784f899b38bf73afbce
