### ISSUE TITLE
Add phylogenetic uncertainty as a coloring option (i.e., branch support)

### ISSUE THREAD

**Issue by sidneymbell** [nextstrain/augur#666]
In the spirit of communicating uncertainty (we should be able to just grab these values out of iqtree and pipe them through as a node attr, right?)

**Comment by jameshadfield** [comment]
There's a few different ways that augur could export this information for display in auspice. I'd be open for extending auspice's functionality here as we have more examples.

1. Add a `branch_support` quantatative colouring, so that each node contains `node_attrs -> branch_support -> value -> X`. This will give you a rainbow colour scale. I used this approach for https://nextstrain.org/mers?c=posterior

2. Add a colouring trait `branch_support` to all nodes using a dummy value, and encode the support in the entropy (`node_attrs -> branch_support -> entropy -> X`). This will give you an opacity ramp for the branches to convey uncertainty.

3. Add branch labels to each internal branch (`branch_attrs -> labels -> support -> X`). This will quickly become unworkable, but may be useful to highlight specific branches.



![image](https://user-images.githubusercontent.com/8350992/105782067-a2923e80-5fd8-11eb-8364-f8e5e5bbe30f.png)
_https://nextstrain.org/mers?c=posterior_

**Comment by sidneymbell** [comment]
@trvrb -- Good point, thanks! Tried to transfer repos (bottom of the right sidebar) but it looks like I don't have the necessary permissions for the `augur` repo for some reason.

Re: bootstrap feasibility, yeah, that's a major issue for big trees. Perhaps one way to address this would be to add the a `--bootstrap` option to `augur tree`, with a warning if the tree has more than N samples? 

@jameshadfield -- thanks for such a thoughtful outline! I wasn't aware of the entropy - opacity relationship, super cool. I think any combination of the three would be great (and this is super configurable in the json config, I imagine).

**Comment by jonbra** [comment]
Displaying node support in Auspice would be extremely useful. @jameshadfield could you provide some more detail on how you created the `branch_support` values in the MERS example you showed? I see [here](https://docs.nextstrain.org/projects/augur/en/stable/api/augur.export_v2.html?highlight=node_attrs#augur.export_v2.set_node_attrs_on_tree) that creating `node_attrs` requires a dictionary with strain names mapped to some data, but it is difficult to link all nodes to the corresponding strain?

I also tried to read a tree with bootstrap values but got the same error as [reported earlier](https://discussion.nextstrain.org/t/view-bootstrap-trees-with-augur-export/86). It seems that Biopython can't parse the support values correctly?

Thanks!

**Comment by jameshadfield** [comment]
@jonbra no problem, the idea is to create a new colouring for display such as "branch_support" (you can choose the name, there's nothing special about that one). Using a custom script in your pipeline, you would create a node-data file which maps nodes to their bootstrap values, i.e. something like this:
```json
{
  "nodes": {
    "NODE_00001": {
      "branch_support": 0.123
    },
    "NODE_00002": {
      "branch_support": 0.456
    },
    ...
```
where the node names are taken from the tree supplied to `augur export v2` (normally this is produced by `augur refine` which annotates the names of internal nodes). You would then define this colouring in the auspice config JSON supplied to `augur export v2` such as:
```json
{
  ...
    "colorings": [
    {
      "key": "branch_support",
      "title": "Bootstrap support",
      "type": "continuous"
    },
    ...
```
Finally, supply both these files to `augur export v2` and you will get a visualisation similar to the MERS screenshot above.

**Comment by mattoslmp** [comment]
@jameshadfield  How can I modify workflow to display the tree similar to the one you generated in MERS?

**Comment by jameshadfield** [comment]
@mattoslmp the MERS dataset came from BEAST, using `augur import beast` which will export posterior support as an auspice colouring. To display bootstrap support you'd need to (a) generate a tree with bootstraps and (b) write a small custom script to extract these into a node-data JSON for `augur export` to consume.

**Comment by mattoslmp** [comment]
@jameshadfield, thank you.  Do you think that is possible change the iqtree (newick) output to node-data JSON? I would like to see my phylogenetic tree generated with iq-tree in the auspice/nextstrain group.
