### ISSUE TITLE
[augur filter] allow `--subsample-max-sequences` without `--group-by`

### ISSUE THREAD

**Issue by jameshadfield** [nextstrain/augur#680]
Currently using `augur filter`'s `--subsample-max-sequences` argument isn't used unless a `--group-by` argument is also specified, as the argument is only used [if this conditional is met](https://github.com/nextstrain/augur/blob/master/augur/filter.py#L314):

```py
if args.group_by and (args.sequences_per_group or args.subsample_max_sequences):
    # subsample the dataset
```

The desired functionality for the case where `--subsample-max-sequences` is set but `--group-by` is not is to group all samples into a dummy group and subsample from that.

**Comment by huddlej** [comment]
To address this issue, we want to revise [the conditional referenced above](https://github.com/nextstrain/augur/blob/24baeaf1f8fa25beefb727bccf21199d33f6b152/augur/filter.py#L379) to pass when `args.subsample_max_sequences` is truthy and define a separate `group_by` variable [to test each strain against](https://github.com/nextstrain/augur/blob/24baeaf1f8fa25beefb727bccf21199d33f6b152/augur/filter.py#L387) which will have the values in `args.group_by` if any are provided or a dummy value otherwise. In the case that we use a dummy value to make a single group, we will need to skip [the current check for whether the group column is in the metadata](https://github.com/nextstrain/augur/blob/24baeaf1f8fa25beefb727bccf21199d33f6b152/augur/filter.py#L388).
