### ISSUE TITLE
augur export v2: meta data file does not exist

### ISSUE THREAD

**Issue by jonbra** [nextstrain/augur#733]
**Current Behavior**  
I followed the steps outlined in the Zika tutorial and successfully completed all the steps. However, when running the final step `augur export v2` I get the error message that the meta data file does not exist. I input the same metadata file that I used in some of the previous steps, and I know it's there because I enter it with autocomplete button. I have also successfully run this command on other datasets. Are there any other reasons this error message might occur besides a missing file?

**How to reproduce**  
```
augur export v2 --tree results/tree.nwk --metadata Metadata_GISAID_all_countries.20210526.tsv --node-data results/branch_lengths.json results/traits.json results/nt_muts.json results/aa_muts.json --colors colors.tsv --auspice-config auspice_config.json --output auspice/Norwegian_foreign_GISAID.json
ERROR: meta data file (Metadata_GISAID_all_countries.20210526.tsv) does not exist
```

**Your environment: if running Nextstrain locally**  
 - Operating system:   Linux Mint  
 - Version: `augur 12.0.0`

**Comment by rneher** [comment]
Thanks for raising this. the Problem likely is that some of the `node-data` files do not exist. The raised exception incorrectly assumed that the missing file is the metadata file.

**Comment by rneher** [comment]
I suspect the problem is here:

https://github.com/nextstrain/augur/blob/master/augur/export_v2.py#L902-L907

@benjaminotter (cc @huddlej), could you have a look?

**Comment by Yiqingzzz** [comment]
Hi，I'm having the same problem.I also get the error message that the meta data file does not exist. Did you solve the problem？

**Comment by jonbra** [comment]
Hi, 
Yes, at least I think so. The error was in fact missing node data as Richard Neher suggested. I had used a different file for one of the node data earlier in the pipeline. So it had nothing to do with metadata.

**Comment by corneliusroemer** [comment]
Just to add, I could reproduce the error. In my case it was also a node-data file missing. The error then falsely reported that the metadata file was missing.

Here's the command I ran:
```
❯ augur export v2             --tree build/tree.nwk             --metadata pre-processed/metadata_enriched.tsv             --node-data build/nt_muts.json build/branch_lengths.json build/aa_muts_explicit.json "build/clock_deviation.json" "build/terminal_branch_length.json"            --include-root-sequence             --auspice-config profiles/b/vic/auspice_config.json             --color-by-metadata continent country fluSeason strainName             --output auspice/auspice.json 2>&1

ERROR: meta data file (pre-processed/metadata_enriched.tsv) does not exist
```
`pre-processed/metadata_enriched.tsv ` was actually present, but `"build/clock_deviation.json" "build/terminal_branch_length.json"   ` were not.

**Comment by huddlej** [comment]
The problematic code here is the overly generalized exception block that catches both missing node data and metadata. A clearer way to implement this would be to restructure [the calling code](https://github.com/nextstrain/augur/blob/89bc02849df47e67441ac005ffadc3c42b72476f/augur/export_v2.py#L963-L967) such that it attempts to load the node data JSON and metadata prior to calling the parser. We should modify the parser to accept loaded node data and metadata [instead of trying to load these from files itself](https://github.com/nextstrain/augur/blob/89bc02849df47e67441ac005ffadc3c42b72476f/augur/export_v2.py#L911-L915).

This parser function only appears to be used by the export module, but it would be worth a quick check of the ncov repo for references in our custom scripts, too.

@benjaminotter, would you have some time to try the implementation I've described above?
