### ISSUE TITLE
MutableSeq conflicts with older versions of BioPython allowed by setup.py

### ISSUE THREAD

**Issue by trvrb** [nextstrain/augur#798]
**Current Behavior**  
Moving to `MutableSeq(seq)` in PR #788 was necessary because BioPython deprecated our previous call to `seq.tomutable()` per #787.

However, just running `pip install -e '.[dev]'` based on `setup.py` was not forcing my BioPython installation to upgrade to match. Because of this I was getting a surprising error:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/augur", line 33, in <module>
    sys.exit(load_entry_point('nextstrain-augur', 'console_scripts', 'augur')())
  File "/Users/trvrb/Documents/src/augur/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/Users/trvrb/Documents/src/augur/augur/__init__.py", line 75, in run
    return args.__command__.run(args)
  File "/Users/trvrb/Documents/src/augur/augur/tree.py", line 371, in run
    aln = mask_sites_in_multiple_sequence_alignment(args.alignment, args.exclude_sites)
  File "/Users/trvrb/Documents/src/augur/augur/tree.py", line 328, in mask_sites_in_multiple_sequence_alignment
    sequence = MutableSeq(record.seq)
  File "/opt/homebrew/lib/python3.9/site-packages/Bio/Seq.py", line 2049, in __init__
    raise TypeError(
TypeError: The sequence data given to a MutableSeq object should be a string or an array (not a Seq object etc)
```

This was with BioPython 1.76. It looks like we'll need to request a quite recent version of BioPython here:

https://github.com/nextstrain/augur/blob/master/setup.py#L51

I confirmed that upgrading locally to BioPython 1.79 fixed the error for me.

I believe this should be considered to be blocking release until resolved.

**Comment by huddlej** [comment]
I’m sorry about this, @trvrb. This bug is partially caused by the inaccuracy of the BioPython deprecation warning for older versions of BioPython:

```
BiopythonDeprecationWarning: myseq.tomutable() is deprecated; please use MutableSeq(myseq) instead.
```

The recommended code above works in 1.79, but it does not work in earlier versions we support. I should have tested this code in the earlier versions. Our CI tests would have caught this issue earlier, if we ran the earliest support BioPython (1.67) in CI.

The decision to [maintain backward support for earlier BioPython versions](https://github.com/nextstrain/augur/issues/763#issuecomment-900535803) is part of [a broader philosophical discussion](https://bedfordlab.slack.com/archives/C01LCTT7JNN/p1638397441299000) that @tsibley and I have been having. Supporting these older versions avoids forcing users to upgrade unnecessarily, but it does increase the responsibility for our development team to test a broader range of possible dependency configurations. Our narrow CI tests do not reflect this additional responsibility. When I run our tests in CI with our earliest supported BioPython, [several other tests fail](https://app.travis-ci.com/github/nextstrain/augur/jobs/551090210#L2616-L2673).

In this specific case, there is a simple fix to this issue that will maintain our backward compatibility with older BioPython versions (casting `Seq` records to strings). I can [merge this fix without requiring any other changes to our dependencies](https://github.com/nextstrain/augur/pull/801) (and Bioconda recipe), but we should probably still have a separate discussion about how to better support older versions of dependencies or whether to narrow our support to just the most recent versions. For example, do we want to have a CI test matrix that tests multiple combinations of BioPython and Python versions? Do we pin the earliest versions of each? Or, do we narrow our supported dependencies to only the most recent versions?

Below is a complete set of tests for this issue with different BioPython versions (starting with 1.67).

```
mamba create -n biopython167 -c conda-forge -c bioconda python=3.6 biopython=1.67
conda activate biopython167

python3 -m pip install -e .[dev]

# Run a specific functional test.
cram --shell=/bin/bash tests/functional/tree.t

# Or just run the command that fails. 
augur tree \
--alignment tests/functional/tree/aligned.fasta \
--method iqtree \
--substitution-model auto \
--exclude-sites tests/functional/tree/excluded_sites.txt \
--output tree_raw.nwk
```

```
Traceback (most recent call last):
  File "/Users/jlhudd/miniconda3/envs/biopython167/bin/augur", line 33, in <module>
    sys.exit(load_entry_point('nextstrain-augur', 'console_scripts', 'augur')())
  File "/Users/jlhudd/projects/nextstrain/augur/augur/__main__.py", line 10, in main
    return augur.run( argv[1:] )
  File "/Users/jlhudd/projects/nextstrain/augur/augur/__init__.py", line 75, in run
    return args.__command__.run(args)
  File "/Users/jlhudd/projects/nextstrain/augur/augur/tree.py", line 371, in run
    aln = mask_sites_in_multiple_sequence_alignment(args.alignment, args.exclude_sites)
  File "/Users/jlhudd/projects/nextstrain/augur/augur/tree.py", line 332, in mask_sites_in_multiple_sequence_alignment
    sequence[site] = "N"
  File "/Users/jlhudd/miniconda3/envs/biopython167/lib/python3.6/site-packages/Bio/Seq.py", line 1688, in __setitem__
    self.data[index] = value
TypeError: 'Seq' object does not support item assignment
```

This bug appears to be caused by BioPython storing the Seq object as the mutable sequence string. Indexing the resulting MutableSeq indexes the Seq object that cannot be modified. The correct implementation is:

```python
sequence = MutableSeq(str(record.seq))
```

Test in Python 3.6 with BioPython 1.67 (oldest supported version):

```python
from Bio.Seq import MutableSeq, Seq
s = Seq("ACTG")

# This should fail.
s[1] = "N"
# TypeError: 'Seq' object does not support item assignment

# This should work (according to BioPython deprecation warning), but it doesn't.
ms = MutableSeq(s)
ms[1] = "N"
# TypeError: 'Seq' object does not support item assignment

# This works instead.
ms = MutableSeq(str(s))
ms[1] = "N"
```

Now, upgrade to the previous version we supported (before 1.79 came out).

```
mamba create -n biopython176 -c conda-forge -c bioconda python=3.6 biopython=1.76
conda activate biopython176

python3 -m pip install -e .[dev]
```

Repeat the Python code above.

```python
from Bio.Seq import MutableSeq, Seq
s = Seq("ACTG")

# This should fail.
s[1] = "N"
# TypeError: 'Seq' object does not support item assignment

# This should work (according to BioPython deprecation warning), but it doesn't.
ms = MutableSeq(s)
# TypeError: The sequence data given to a MutableSeq object should be a string or an array (not a Seq object etc)

# This works instead.
ms = MutableSeq(str(s))
ms[1] = "N"
```

The behavior of `MutableSeq` changed from 1.67 to 1.76, causing an error when using a `Seq` object to initialize a new `MutableSeq` instead of failing later when trying to modify the mutable sequence.

Next, upgrade to BioPython 1.79 and repeat.

```python
from Bio.Seq import MutableSeq, Seq
s = Seq("ACTG")

# This should fail.
s[1] = "N"
# TypeError: 'Seq' object does not support item assignment

# This should work (according to BioPython deprecation warning), and it does work now.
ms = MutableSeq(s)
ms[1] = "N"

# This still works, too.
ms = MutableSeq(str(s))
ms[1] = "N"
```

**Comment by tsibley** [comment]
To followup, let me say that I imagine such a test matrix to be defined conceptually by a list of packages to test ~exhaustively. This would probably be just `biopython` and `pandas` to start?

Our test framework would then use our package metadata to grab a version req specs with PyPI index data to expand each dep into a list of actual versions of test. As an optimization, for deps we know to reliable about semantic versions (e.g. not BioPython but maybe Pandas), it could do some pruning of versions we assume to be equivalent.
