### ISSUE TITLE
read_metadata: Allow graceful handling of duplicate strain names

### ISSUE THREAD

**Issue by corneliusroemer** [nextstrain/augur#810]
**Context**  
I'm using GISAID's data export for Augur. Someone uploaded two different sequences with different EPI ISLs but the same strain name. This causes augur's `read_metadata` to crash here:
```
def check_metadata_duplicates(self):
        duplicates = (
            self.metadata[self.key_type]
            .value_counts()
            .reset_index()
            .query(f"{self.key_type} > 1")["index"]
            .values
        )

        if len(duplicates) > 0:
            raise ValueError(
                f"Duplicated {self.key_type} in metadata: {', '.join(duplicates)}"
            )
```

It would be good if there was a flag that one could set to be happy with duplicates and just choose the first (or last or none.

Because now I need to manually remove this duplicate or run a different script to deduplicate the metadata myself. It can be done but it'd be nice if the util had a flag taking care of this.

**Comment by tsibley** [comment]
Consider `augur curate`'s standardized duplicate handling option:

https://github.com/nextstrain/augur/blob/18e07b4615cbd06edac9562ce94e4b63c746a4bb/augur/curate/__init__.py#L79-L83

https://github.com/nextstrain/augur/blob/18e07b4615cbd06edac9562ce94e4b63c746a4bb/augur/types.py#L39-L49

**Comment by trvrb** [comment]
Re-upping this here in the context of `augur filter`. My guess had been that `augur filter` would de-duplicate entries, but I just discovered in the context of [augur merge review](https://github.com/nextstrain/augur/pull/1563#discussion_r1714489128) that metadata and sequences are handled differently in augur filter.

For metadata I tested by doubling entries in `metadata.tsv` from zika and then ran a simple `augur filter` command:
```
augur filter --sequences sequences.fasta --metadata metadata_doubled.tsv --output-sequences test.fasta --output-metadata test.tsv
```
this errors out `ERROR: The following strains are duplicated in 'metadata_doubled.tsv':`. This makes sense as otherwise further commands like `augur refine` won't know which entry to use.

For sequences I tested by doubling entries in `sequences.fasta` and then ran a similar filter command:
```
augur filter --sequences sequences_doubled.fasta --metadata metadata.tsv --output-sequences test.fasta --output-metadata test.tsv
```
Here, there's no complaints. The resulting files have _n_ entries in `test.tsv` and 2 _n_ entries in `test.fasta`.

I think we should be consistent with behavior for sequences and metadata and error out if there are duplicate sequences when running `augur filter`.

**Comment by victorlin** [comment]
@trvrb thanks for resurfacing this. Zooming out a bit, there have been several issues where de-duplication has been discussed:

- #586
- #725
- #810 (this issue)
- #919
- #616

#586, #725, and #810 all seem to be discussing the same thing: allow **existing** Augur commands to handle de-duplication.

#919 and #616 are separately similar: create a **new** Augur command to handle de-duplication.

The current status quo and consensus used by most commands is well summarized by @huddlej in https://github.com/nextstrain/augur/issues/616#issuecomment-1040889090:

> We should try to keep Augur commands as tightly scoped as possible to solve specific problems. Resolving duplicates should be outside the responsibilities of the `parse` command; another Augur command should be responsible for deduplicating/sanitizing sequences and metadata.

Based on that, the solution here is to close #586, #725, and #810 as "not planned". Separately, as pointed out in the previous comment, there is a bug in `augur filter` where `--output-sequences` allows duplicates to pass through. This should be fixed to error on duplicates.

**Comment by trvrb** [comment]
Thanks for the write up @victorlin! `augur merge --sequences` would handle de-duplication naturally and would seem to be a good place for it to live.

**Comment by victorlin** [comment]
Closing this as not planned per https://github.com/nextstrain/augur/issues/810#issuecomment-2286856280
