### ISSUE TITLE
Augur align issue: Unable to run shell commands using env and bash

### ISSUE THREAD

**Issue by kwongm** [nextstrain/augur#876]
**Current Behavior**
Running a workflow, and currently trying to run the Augur align step.

augur align --sequences results\filtered.fasta --output\results\aligned.fasta --fill-gaps

**Expected behavior**
Expected to produce aligned.fasta.

**Environment**
 - Operating system: WIndows 10
 - Running on Python 3.9.7 environment, out of Visual Studio Code in conda environment.
- Versions
-- augur 14.0.0
-- auspice 2.35.0
-- snakemake-minimal 7.2.1
![augur align error](https://user-images.githubusercontent.com/50677592/159374683-6976bb30-eb25-4870-9ff5-53aefa99a18d.jpg)

**Comment by huddlej** [comment]
Hi @kwongm, I've transferred this issue to the augur repository, since it appears to be unrelated to the ncov workflow (which uses `nextalign` instead of `augur align`).

The augur tools require a UNIX-like operating system, so they don't run natively on Windows terminal. However, if you follow [the Nextstrain installation instructions for Windows](https://docs.nextstrain.org/en/latest/install.html#installation-steps), you should be able to run your Nextstrain workflows through [the `nextstrain build` command](https://docs.nextstrain.org/projects/cli/en/stable/commands/build/) or test out specific augur commands by running [the `nextstrain shell` command](https://docs.nextstrain.org/projects/cli/en/stable/commands/shell/).

These commands work on Windows because they rely on a Linux-based Docker image that has all of our Nextstrain tools installed, so when you run these commands, augur will execute in the Linux environment rather than the Windows environment.

Let me know here if this approach doesn't end up working, and we can try to figure out another approach.
