### ISSUE TITLE
dates: Clarify intended date format support by `DateDisambiguator`

### ISSUE THREAD

**Issue by victorlin** [nextstrain/augur#989]
This discussion is motivated by https://github.com/nextstrain/augur/pull/928#discussion_r904362770, where regular expressions are being written to try and define acceptable date formats.

This is the current (not necessarily desired) behavior for parsing dates in metadata:

```py
from augur.util_support.date_disambiguator import DateDisambiguator
DateDisambiguator("2020-01-01").range() # (datetime.date(2020, 1, 1), datetime.date(2020, 1, 1))
DateDisambiguator("2020-01-0X").range() # (datetime.date(2020, 1, 1), datetime.date(2020, 1, 9))
DateDisambiguator("2020-01-X1").range() # (datetime.date(2020, 1, 1), datetime.date(2020, 1, 31))
DateDisambiguator("2020-0X-XX").range() # (datetime.date(2020, 1, 1), datetime.date(2020, 9, 30))
DateDisambiguator("2020-X1-XX").range() # (datetime.date(2020, 1, 1), datetime.date(2020, 12, 31))
DateDisambiguator("202X-XX-XX").range() # (datetime.date(2020, 1, 1), datetime.date(2022, 6, 23))
DateDisambiguator("20X0-XX-XX").range() # (datetime.date(2000, 1, 1), datetime.date(2022, 6, 23))
DateDisambiguator("XXX0-XX-XX").range() # (datetime.date(1, 1, 1), datetime.date(2022, 6, 23))
DateDisambiguator("XXXX-XX-XX").range() # (datetime.date(1, 1, 1), datetime.date(2022, 6, 23))
DateDisambiguator("2020-00-99").range() # (datetime.date(2020, 1, 31), datetime.date(2020, 1, 31))
DateDisambiguator("2020-XX-01").range() # ValueError: Invalid date: Month contains uncertainty, so day must also be uncertain.
DateDisambiguator("202X-01-01").range() # ValueError: Invalid date: Year contains uncertainty, so month and day must also be uncertain.
```

Open for discussion: is it beneficial to **continue** supporting the following?

1. partial ambiguity in month/day when `X` comes before a digit (e.g. `2020-01-X1`)
2. partial ambiguity in month/day when `X` comes after a digit (e.g. `2020-01-0X`)
3. partial ambiguity in year when `X` comes before a digit (e.g. `20X0-XX-XX`)
4. partial ambiguity in year when `X` comes after a digit (e.g. `202X-XX-XX`)
5. mapping out-of-bounds values to the closest in-bound values (e.g. `2020-00-99` -> `2020-01-31`)

**Comment by tsibley** [comment]
My 2¢—others will have a much better sense of what's useful in actual practice—is that it'd be ok to ditch the additional complexity of partial ambiguity and just allow full ambiguity for the month and day parts. This may result in "losing" some information if the date really is known to be, e.g., `2020-01-1X` but we can only treat it as `2020-01-XX`, but that seems like an acceptable tradeoff to me? It'd be nice to know if partial ambiguity is used to better weigh the tradeoff, which is where folks with hands-on experience will have good insight.

If we _do_ allow partial ambiguity, I think it's very reasonable to avoid the complexity of supporting cases where an X comes before a digit (e.g. the ambiguity is a more significant "digit" than the known digits). The current behaviour here doesn't totally make sense to me, for example:

- 2020-X1-XX maps to [2020-01-01, 2020-12-31] but I'd think it should be [2020-11-01, 2020-11-30] instead? (I think I know why it happens (X1 → 91 then out-of-bounds recovery from 91 → 12), but that doesn't mean it makes sense.)
- 2020-X2-XX maps to [2020-02-01, 2020-12-31] but more correctly would be a discontinuous range of [2020-02-01, 2020-02-29] + [2020-12-01, 2020-12-31].

If we're not going to rectify the examples of partial ambiguity above, then I think it's more misleading to allow it and treat it as almost full ambiguity.

I think it's more helpful to reject dates with out-of-bounds parts instead of quietly mapping them to something else. These are a data quality issue more than anything and should be addressed explicitly IMO.

All of the above are thoughts on what we should accept for _analysis_ (arguments, parameters, metadata on which we do computations, etc). For `augur curate` commands to normalize and clean up dates, we should be much more liberal and help map partially-ambiguous and out-of-bounds and more to acceptable values for analysis.

**Comment by victorlin** [comment]
@tsibley thanks for the comments, I agree with everything. This highlights the liberal but messy date format support currently. Would be nice to trim it down and let `augur curate` handle all the weird cases.

**Comment by huddlej** [comment]
I'm most familiar with seasonal flu data where I've never seen dates with the kind of partial ambiguity described above. I agree that these should be treated as a data quality issue and as fully ambiguous at the appropriate resolution (e.g., `YYYY-XM-DD` -> `YYYY-XX-XX` and `YYYY-MM-XD` -> `YYYY-MM-XX`).

**Comment by j23414** [comment]
Of the five cases, I've maybe seen 1 and 5: 
1. `2020-01-X1` - someone has a bug in their curation script before they passed me the file. I'm fine with it being converted to `2020-01-XX` or `2020-01-01` (I'll have to think about `2020-01-11`)
5. looked more like`2020-02-31 -> 2020-02-28` - someone is probably automatically generating metadata and it's probably a typo in GenBank

**Comment by emmahodcroft** [comment]
Of these I've only seen 2 and 4, though I wonder if 3 is also related to 4 in a way that I've seen.

For 2 - `2020-01-0X` - I've seen this only very rarely but when people didn't want to pass more detailed date information (linking/privacy concerns) (and prior to SC2 when we just started telling people more often that it was fine to 'jiggle' dates by a few days) - I usually saw it as `2020-01-1X` or `2020-01-2X` as this gives a spaces of ~10 days when the sample could be from.  I don't see that this exists anymore in my D68 data though. Depending on the mutation rate of the pathogen this may (?) be useful if it gets things narrower than a month? But I don't know what the overhead of continuing to support it is. So I'd say I do see a real use case (privacy/linking) but whether it's 'worth it' is another question.

For 4 - `202X-XX-XX` - I've used this (also D68) when one could kind of infer a decade (when pulling sample dates out of paper that say useful things like 'samples were gathered between 1992 and 1998' - we don't have a way to be more exacting but restricting to '90s' seemed better than nothing?). However it seems like I've either removed or refined the dates of these from my current dataset. So again, I think it could be 'legit'.

I was wondering if for 3 (`20X0-XX-XX`), is this combined with 4 to make accepting dates like `20XX-XX-XX` and `19XX-XX-XX` allowable? As those ones can actually be quite useful. However, if these 'decade-year' ambiguities are handled separately, then I'd say I can't really see a real use-case for 3.
I also don't see a lot of use for 1.

As @j23414 notes, 5 seems like it might help automated date processing/generating. But not sure I've ever actually managed to generate such weird dates (seems like using any date-object or library would prevent this), and I agree with @tsibley that I think it's likely better to be explicit about this being nonsensical and perhaps better to help people do that kind of 'fixing' in another command.

**Comment by jameshadfield** [comment]
Adding another vote for _not_ including any partial ambiguity. I've never seen dates used like this in bioinformatics and if I did I would always think it's a QC issue.

**Comment by victorlin** [comment]
Thanks for the comments here. I'll conclude that there should not be any partial ambiguity for date parsing in these parts of Augur:

1. `--min-date`/`--max-date` arguments to `augur filter` and `augur frequencies`
2. Parsing of a date column in metadata passed as input to `augur filter`, `augur frequencies`, and `augur refine`

I'll make PRs accordingly.

**Comment by victorlin** [comment]
A related thought while documenting #1136: `--year-bounds` (in theory) relies on support for partial ambiguity in the year, though the logic could be improved (i.e. check for presence of `X`, not `XX`).

**Comment by victorlin** [comment]
The decision to re-implement functionality of `--year-bounds` in #1136 requires partial ambiguity.

I'm updating the conclusion here from "do not allow any partial ambiguity" to "allow partial ambiguity only where `X` comes after digits" (e.g. `201X` but not `20X0`).

As for the out-of-bounds mapping, I plan to treat that as user error.

This should be reflected in #928 and another PR which consolidates the date parsing logic.
